<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>PrintLayoutAddin.LicenseGenerator</RootNamespace>
    <AssemblyName>PLLicenseGen</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
